/**
 * Anime heroes. Bought with Wins only, purely cosmetic - they never change speed.
 *
 * `look` drives the procedural model (game/hero/buildHero.js) and `aura` drives the
 * effect stack (game/hero/Aura.jsx). Every hero has its own palette, hair, gear and
 * aura style so no two read alike.
 *
 * Aura particle patterns: rise | orbit | spiral | fall | sparkle
 * Particle shapes:        dot | ember | petal | star | shard | leaf
 */

export const RARITIES = {
  common: { label: 'Common', color: '#b8c4d6', glow: '#e3ecf7' },
  rare: { label: 'Rare', color: '#3aa6ff', glow: '#8fd0ff' },
  epic: { label: 'Epic', color: '#b04dff', glow: '#dba6ff' },
  legendary: { label: 'Legendary', color: '#ffb31a', glow: '#ffe08a' },
  mythic: { label: 'Mythic', color: '#ff3b6b', glow: '#ff9bb4' },
  secret: { label: 'Secret', color: '#20f0c8', glow: '#b6fff0' },
}

export const HEROES = [
  {
    id: 'kaito',
    name: 'Kaito Blaze',
    title: 'Flame Swordsman',
    rarity: 'common',
    price: 25,
    look: {
      skin: '#f6d2b0',
      hair: '#e0301e',
      hairTip: '#ffb020',
      hairStyle: 'spiky',
      eye: '#ff6a00',
      top: '#1d1f2b',
      topAccent: '#ff7a1a',
      pants: '#2c2f3d',
      shoes: '#15161d',
      gear: ['blades', 'belt'],
      glow: '#ff7a1a',
    },
    aura: {
      color: '#ff5a14',
      color2: '#ffd23a',
      shell: 0.9,
      ring: true,
      particles: [
        { pattern: 'rise', shape: 'ember', count: 70, size: 0.16, a: '#ffdd55', b: '#ff2200', speed: 1.2 },
      ],
    },
  },
  {
    id: 'yuki',
    name: 'Yuki Frost',
    title: 'Ice Maiden',
    rarity: 'common',
    price: 60,
    look: {
      skin: '#fbe3d2',
      hair: '#dff4ff',
      hairTip: '#6fd0ff',
      hairStyle: 'long',
      eye: '#3fc8ff',
      top: '#8fd3ff',
      topAccent: '#ffffff',
      pants: '#e9f6ff',
      shoes: '#5aa9e6',
      gear: ['crown', 'gauntlets'],
      glow: '#6fe3ff',
    },
    aura: {
      color: '#63d8ff',
      color2: '#ffffff',
      shell: 0.6,
      ring: true,
      particles: [
        { pattern: 'orbit', shape: 'shard', count: 18, size: 0.3, a: '#ffffff', b: '#63d8ff', speed: 0.8 },
        { pattern: 'fall', shape: 'star', count: 60, size: 0.1, a: '#ffffff', b: '#a8ecff', speed: 0.5 },
      ],
    },
  },
  {
    id: 'raiden',
    name: 'Raiden Volt',
    title: 'Thunder Ninja',
    rarity: 'rare',
    price: 120,
    look: {
      skin: '#f2c9a1',
      hair: '#ffe23a',
      hairTip: '#ffffff',
      hairStyle: 'spiky',
      eye: '#33e6ff',
      top: '#18214a',
      topAccent: '#ffe23a',
      pants: '#111733',
      shoes: '#0a0e22',
      gear: ['headband', 'scarf'],
      glow: '#3ff0ff',
    },
    aura: {
      color: '#2fd6ff',
      color2: '#fff45a',
      shell: 0.8,
      ring: true,
      lightning: { color: '#9ff4ff', count: 4 },
      particles: [
        { pattern: 'sparkle', shape: 'star', count: 50, size: 0.14, a: '#ffffff', b: '#2fd6ff', speed: 2 },
      ],
    },
  },
  {
    id: 'sakura',
    name: 'Sakura Hana',
    title: 'Blossom Blade',
    rarity: 'rare',
    price: 229,
    look: {
      skin: '#fde0cf',
      hair: '#ff7fbf',
      hairTip: '#ffd1ea',
      hairStyle: 'twintails',
      eye: '#ff3d9a',
      top: '#ffffff',
      topAccent: '#ff5fae',
      pants: '#ff9ccd',
      shoes: '#c93f86',
      gear: ['katana', 'belt'],
      glow: '#ff7fcf',
    },
    aura: {
      color: '#ff6fc0',
      color2: '#ffe0f2',
      shell: 0.55,
      ring: true,
      particles: [
        { pattern: 'spiral', shape: 'petal', count: 60, size: 0.22, a: '#ffd6ec', b: '#ff5fae', speed: 0.7 },
        { pattern: 'fall', shape: 'petal', count: 30, size: 0.18, a: '#ffe8f4', b: '#ff8cc8', speed: 0.4 },
      ],
    },
  },
  {
    id: 'shade',
    name: 'Shade Noctis',
    title: 'Void Assassin',
    rarity: 'epic',
    price: 400,
    look: {
      skin: '#e8c4a8',
      hair: '#16121f',
      hairTip: '#9b4dff',
      hairStyle: 'hood',
      eye: '#c04dff',
      top: '#17121f',
      topAccent: '#9b4dff',
      pants: '#100c16',
      shoes: '#07050a',
      gear: ['cape', 'mask', 'blades'],
      glow: '#a855ff',
    },
    aura: {
      color: '#8a2dff',
      color2: '#ff4dd8',
      shell: 1.1,
      ring: true,
      orbitRings: 2,
      particles: [
        { pattern: 'rise', shape: 'dot', count: 80, size: 0.24, a: '#c77dff', b: '#2a0050', speed: 0.8 },
        { pattern: 'orbit', shape: 'dot', count: 12, size: 0.2, a: '#ff7df0', b: '#8a2dff', speed: 1.6 },
      ],
    },
  },
  {
    id: 'jade',
    name: 'Jade Viper',
    title: 'Emerald Monk',
    rarity: 'epic',
    price: 650,
    look: {
      skin: '#e6b98f',
      hair: '#0f7a4a',
      hairTip: '#6bff9e',
      hairStyle: 'topknot',
      eye: '#5dff8f',
      top: '#1f8f58',
      topAccent: '#f2d64a',
      pants: '#14573a',
      shoes: '#0b2e1f',
      gear: ['gauntlets', 'belt', 'beads'],
      glow: '#4dff8a',
    },
    aura: {
      color: '#2dff7a',
      color2: '#d6ff4d',
      shell: 0.85,
      ring: true,
      runes: true,
      particles: [
        { pattern: 'spiral', shape: 'leaf', count: 70, size: 0.18, a: '#c8ff6b', b: '#1bd660', speed: 1.1 },
      ],
    },
  },
  {
    id: 'aurelia',
    name: 'Aurelia Dawn',
    title: 'Holy Knight',
    rarity: 'legendary',
    price: 1000,
    look: {
      skin: '#fbe0c8',
      hair: '#ffd36b',
      hairTip: '#fff4c4',
      hairStyle: 'ponytail',
      eye: '#ffc93a',
      top: '#f6f3ea',
      topAccent: '#e8b12a',
      pants: '#e9e2cf',
      shoes: '#b8871a',
      gear: ['halo', 'shoulders', 'wings'],
      glow: '#ffe07a',
    },
    aura: {
      color: '#ffd84d',
      color2: '#ffffff',
      shell: 0.9,
      ring: true,
      pillar: true,
      orbitRings: 1,
      particles: [
        { pattern: 'rise', shape: 'star', count: 60, size: 0.16, a: '#ffffff', b: '#ffcc33', speed: 0.9 },
        { pattern: 'sparkle', shape: 'star', count: 40, size: 0.12, a: '#fff7c2', b: '#ffd84d', speed: 1.5 },
      ],
    },
  },
  {
    id: 'crimson',
    name: 'Crimson Rex',
    title: 'Blood Moon Berserker',
    rarity: 'legendary',
    price: 1500,
    look: {
      skin: '#e2b08a',
      hair: '#b3001e',
      hairTip: '#ff4d4d',
      hairStyle: 'messy',
      eye: '#ff1a3c',
      top: '#3a0710',
      topAccent: '#ff2a44',
      pants: '#1c0508',
      shoes: '#0d0204',
      gear: ['horns', 'scarf', 'blades'],
      glow: '#ff2a44',
    },
    aura: {
      color: '#ff1437',
      color2: '#5a0010',
      shell: 1.2,
      ring: true,
      orbitRings: 1,
      particles: [
        { pattern: 'orbit', shape: 'dot', count: 10, size: 0.34, a: '#ff6078', b: '#b3001e', speed: 1.2 },
        { pattern: 'rise', shape: 'ember', count: 70, size: 0.15, a: '#ff5a5a', b: '#3a0008', speed: 1.4 },
      ],
    },
  },
  {
    id: 'nova',
    name: 'Nova Starlight',
    title: 'Galaxy Idol',
    rarity: 'mythic',
    price: 2500,
    requires: { rebirths: 1 },
    look: {
      skin: '#fde2d4',
      hair: '#5b3cff',
      hairTip: '#ff6bf2',
      hairStyle: 'twintails',
      eye: '#ff7bf6',
      top: '#1c1446',
      topAccent: '#6de9ff',
      pants: '#2a1d66',
      shoes: '#ff6bf2',
      gear: ['stars', 'wings'],
      glow: '#8a7dff',
    },
    aura: {
      color: '#7d5bff',
      color2: '#ff6bf2',
      shell: 1,
      ring: true,
      orbitRings: 2,
      particles: [
        { pattern: 'orbit', shape: 'star', count: 26, size: 0.26, a: '#ffffff', b: '#ff9bf7', speed: 0.9 },
        { pattern: 'sparkle', shape: 'star', count: 90, size: 0.11, a: '#ffffff', b: '#8ad8ff', speed: 1.2 },
      ],
    },
  },
  {
    id: 'zephyr',
    name: 'Zephyr Gale',
    title: 'Storm Titan Slayer',
    rarity: 'mythic',
    price: 4000,
    requires: { rebirths: 2 },
    look: {
      skin: '#f0cba8',
      hair: '#e8f0f2',
      hairTip: '#56f0d0',
      hairStyle: 'slick',
      eye: '#40ffd0',
      top: '#23443f',
      topAccent: '#56f0d0',
      pants: '#1b2d2a',
      shoes: '#0d1b19',
      gear: ['scarf', 'blades', 'gear'],
      glow: '#56f0d0',
    },
    aura: {
      color: '#3dffd2',
      color2: '#ffffff',
      shell: 1,
      ring: true,
      lightning: { color: '#c8fff2', count: 2 },
      particles: [
        { pattern: 'spiral', shape: 'dot', count: 110, size: 0.12, a: '#ffffff', b: '#3dffd2', speed: 2.2 },
      ],
    },
  },
  {
    id: 'prism',
    name: 'Prism Kai',
    title: 'Rainbow Spirit',
    rarity: 'secret',
    price: 7500,
    requires: { world2: true },
    look: {
      skin: '#fbe3d6',
      hair: '#ffffff',
      hairTip: 'rainbow',
      hairStyle: 'spiky',
      eye: 'rainbow',
      top: '#f7f7ff',
      topAccent: 'rainbow',
      pants: '#dcdcf5',
      shoes: '#ffffff',
      gear: ['halo', 'cape'],
      glow: '#ffffff',
    },
    aura: {
      color: 'rainbow',
      color2: '#ffffff',
      shell: 1.1,
      ring: true,
      orbitRings: 3,
      particles: [
        { pattern: 'spiral', shape: 'star', count: 90, size: 0.16, a: 'rainbow', b: '#ffffff', speed: 1.4 },
        { pattern: 'sparkle', shape: 'dot', count: 60, size: 0.12, a: 'rainbow', b: '#ffffff', speed: 2 },
      ],
    },
  },
  {
    id: 'ragnar',
    name: 'Ragnar Sol',
    title: 'Titan King',
    rarity: 'secret',
    price: 15000,
    requires: { world2: true, rebirths: 5 },
    look: {
      skin: '#3a1a12',
      hair: '#ff8a00',
      hairTip: '#fff06a',
      hairStyle: 'flame',
      eye: '#fff06a',
      top: '#2a0e08',
      topAccent: '#ff8a00',
      pants: '#1a0805',
      shoes: '#0c0402',
      gear: ['cracks', 'shoulders', 'crown', 'cape'],
      glow: '#ff9a1a',
    },
    aura: {
      color: '#ff8a00',
      color2: '#fff06a',
      shell: 1.4,
      ring: true,
      pillar: true,
      orbitRings: 2,
      lightning: { color: '#ffd27a', count: 3 },
      particles: [
        { pattern: 'rise', shape: 'ember', count: 110, size: 0.2, a: '#fff06a', b: '#ff2a00', speed: 1.6 },
        { pattern: 'orbit', shape: 'dot', count: 8, size: 0.4, a: '#ffe27a', b: '#ff6a00', speed: 0.7 },
      ],
    },
  },
]

export const HERO_BY_ID = Object.fromEntries(HEROES.map((h) => [h.id, h]))

/** Sentinel for "play as my own Bloxity avatar". */
export const AVATAR_ID = 'avatar'
